- name: Commit config
  hosts: all
  collections:
    - juniper.device
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Pushing config ... please wait
      juniper_junos_config:
       check: true
       commit: true
       diff: true
       src: "{{ inventory_hostname }}.conf"
       load: "override"
       comment: Changed using ansible. See commit for details.
       format: "text"
      register: response

    - name: Display diff
      debug:
        var: response


